import Header from '@/components/Header';
import './globals.scss'
import type { Metadata } from 'next'
import { Hanken_Grotesk } from 'next/font/google'

const hankenGrotesk = Hanken_Grotesk({ subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Joshua Greene',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={hankenGrotesk.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
